tteteettes

diff --git a/.github/workflows/e2e-testing-deployment.yml b/.github/workflows/e2e-testing-deployment.yml
--- a/.github/workflows/e2e-testing-deployment.yml
+++ b/.github/workflows/e2e-testing-deployment.yml
@@ -6,68 +6,68 @@ on:
 
 jobs:
 
-  test_docker_compose_network:
-    name: TEST network
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install Node.js HTTP-Server, wait-port
-        run: yarn global add wait-port
-
-      - name: Clone Basilisk-api
-        run: git clone -b feature/change-indexer-ws-provider-url https://github.com/galacticcouncil/Basilisk-api.git
-
-      - name: Cache Node Modules for Basilisk-api
-        id: cache-node-modules-basilisk-api
-        uses: actions/cache@v2
-        with:
-          path: Basilisk-api/node_modules
-          key: node-modules-basilisk-api-${{ hashFiles('Basilisk-api/yarn.lock') }}
-
-      - name: Install Dependencies for Basilisk-api
-        if: steps.cache-node-modules-basilisk-api.outputs.cache-hit != 'true'
-        run: |
-          cd Basilisk-api
-          yarn
-
-      - name: Run Indexer
-        shell: bash
-        run: |
-          cd Basilisk-api
-          yarn run indexer:start-ci-linux &
-
-      - name: Wait for Indexer port :4010
-        shell: bash
-        timeout-minutes: 5
-        run: wait-port 4010
-
-
-      - name: Sleep for 30 seconds
-        run: sleep 30s
-        shell: bash
-
-      - name: docker ps
-        run: docker ps
-        shell: bash
-
-      - name: Get ips list
-        if: always()
-        shell: bash
-        timeout-minutes: 3
-        run: |
-          cd Basilisk-api/indexer
-          docker compose exec -T indexer /bin/sh
-          cat /etc/hosts
-          exit
-
-      - name: Get host ip
-        if: always()
-        shell: bash
-        timeout-minutes: 3
-        run: |
-          cd Basilisk-api/indexer
-          docker compose exec -T indexer /bin/sh
-          sudo apt-get update > /dev/null && sudo apt-get install iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
-          exit
+#  test_docker_compose_network:
+#    name: TEST network
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Install Node.js HTTP-Server, wait-port
+#        run: yarn global add wait-port
+#
+#      - name: Clone Basilisk-api
+#        run: git clone -b feature/change-indexer-ws-provider-url https://github.com/galacticcouncil/Basilisk-api.git
+#
+#      - name: Cache Node Modules for Basilisk-api
+#        id: cache-node-modules-basilisk-api
+#        uses: actions/cache@v2
+#        with:
+#          path: Basilisk-api/node_modules
+#          key: node-modules-basilisk-api-${{ hashFiles('Basilisk-api/yarn.lock') }}
+#
+#      - name: Install Dependencies for Basilisk-api
+#        if: steps.cache-node-modules-basilisk-api.outputs.cache-hit != 'true'
+#        run: |
+#          cd Basilisk-api
+#          yarn
+#
+#      - name: Run Indexer
+#        shell: bash
+#        run: |
+#          cd Basilisk-api
+#          yarn run indexer:start-ci-linux &
+#
+#      - name: Wait for Indexer port :4010
+#        shell: bash
+#        timeout-minutes: 5
+#        run: wait-port 4010
+#
+#
+#      - name: Sleep for 30 seconds
+#        run: sleep 30s
+#        shell: bash
+#
+#      - name: docker ps
+#        run: docker ps
+#        shell: bash
+#
+#      - name: Get ips list
+#        if: always()
+#        shell: bash
+#        timeout-minutes: 3
+#        run: |
+#          cd Basilisk-api/indexer
+#          docker compose exec -T indexer /bin/sh
+#          cat /etc/hosts
+#          exit
+#
+#      - name: Get host ip
+#        if: always()
+#        shell: bash
+#        timeout-minutes: 3
+#        run: |
+#          cd Basilisk-api/indexer
+#          docker compose exec -T indexer /bin/sh
+#          sudo apt-get update > /dev/null && sudo apt-get install iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
+#          exit
 
   #          apk update > /dev/null && apk add iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
 
@@ -84,81 +84,81 @@ jobs:
 #          image: subsquid/hydra-indexer:5
 #          run: cat /etc/hosts
 
-  set_test_env_polkadot_node:
-    name: Set test environment - Polkadot-node
-    runs-on: ubuntu-latest
-    steps:
-
-      - name: Clone Polkadot-node
-        run: |
-          git clone https://github.com/paritytech/polkadot.git
-
-      - name: Cache binary file for Polkadot-node
-        id: cache-bin-polkadot-node
-        uses: actions/cache@v2
-        with:
-          path: polkadot/target/release
-          key: bin-polkadot-node-3-${{ hashFiles('polkadot/Cargo.lock') }}
-
-      - name: Fetch Polkadot-node bin file
-        if: steps.cache-bin-polkadot-node.outputs.cache-hit != 'true'
-        run: |
-          cd polkadot
-          mkdir -p target
-          cd target
-          mkdir -p release
-          cd release
-          wget https://github.com/paritytech/polkadot/releases/download/v0.9.13/polkadot
-
-      - name: Make Polkadot-node bin executanle
-        run: |
-          cd polkadot/target/release
-          chmod +x polkadot
-
-      - name: Save artifacts - Polkadot-node
-        uses: actions/upload-artifact@v2
-        with:
-          name: polkadot-node-artifacts
-          path: ./polkadot/target/release
-
-  set_test_env_basilisk_node:
-    name: Set test environment - Basilisk-node
-    runs-on: ubuntu-latest
-    steps:
-      - name: Clone Basilisk-node
-        run: |
-          git clone https://github.com/galacticcouncil/Basilisk-node.git
-
-      - name: Cache binary file for Basilisk-node
-        id: cache-bin-basilisk-node
-        uses: actions/cache@v2
-        with:
-          path: Basilisk-node/target/release
-          key: bin-basilisk-node-5-${{ hashFiles('Basilisk-node/Cargo.lock') }}
-
-      - name: Fetch Basilisk-node bin file
-        if: steps.cache-bin-basilisk-node.outputs.cache-hit != 'true'
-        run: |
-          cd Basilisk-node
-          mkdir -p target
-          cd target
-          mkdir -p release
-          cd release
-          wget https://github.com/galacticcouncil/Basilisk-node/releases/download/v6.0.0/basilisk
-          cp -v basilisk testing-basilisk
-          ls
-
-      - name: Make Basilisk-node bin executanle
-        run: |
-          cd Basilisk-node/target/release
-          chmod +x basilisk
-          chmod +x testing-basilisk
-
-      - name: Save artifacts - Basilisk-node
-        uses: actions/upload-artifact@v2
-        with:
-          name: basilisk-node-artifacts
-          path: ./Basilisk-node
+#  set_test_env_polkadot_node:
+#    name: Set test environment - Polkadot-node
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#      - name: Clone Polkadot-node
+#        run: |
+#          git clone https://github.com/paritytech/polkadot.git
+#
+#      - name: Cache binary file for Polkadot-node
+#        id: cache-bin-polkadot-node
+#        uses: actions/cache@v2
+#        with:
+#          path: polkadot/target/release
+#          key: bin-polkadot-node-3-${{ hashFiles('polkadot/Cargo.lock') }}
+#
+#      - name: Fetch Polkadot-node bin file
+#        if: steps.cache-bin-polkadot-node.outputs.cache-hit != 'true'
+#        run: |
+#          cd polkadot
+#          mkdir -p target
+#          cd target
+#          mkdir -p release
+#          cd release
+#          wget https://github.com/paritytech/polkadot/releases/download/v0.9.13/polkadot
+#
+#      - name: Make Polkadot-node bin executanle
+#        run: |
+#          cd polkadot/target/release
+#          chmod +x polkadot
+#
+#      - name: Save artifacts - Polkadot-node
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: polkadot-node-artifacts
+#          path: ./polkadot/target/release
+#
+#  set_test_env_basilisk_node:
+#    name: Set test environment - Basilisk-node
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Clone Basilisk-node
+#        run: |
+#          git clone https://github.com/galacticcouncil/Basilisk-node.git
+#
+#      - name: Cache binary file for Basilisk-node
+#        id: cache-bin-basilisk-node
+#        uses: actions/cache@v2
+#        with:
+#          path: Basilisk-node/target/release
+#          key: bin-basilisk-node-5-${{ hashFiles('Basilisk-node/Cargo.lock') }}
+#
+#      - name: Fetch Basilisk-node bin file
+#        if: steps.cache-bin-basilisk-node.outputs.cache-hit != 'true'
+#        run: |
+#          cd Basilisk-node
+#          mkdir -p target
+#          cd target
+#          mkdir -p release
+#          cd release
+#          wget https://github.com/galacticcouncil/Basilisk-node/releases/download/v6.0.0/basilisk
+#          cp -v basilisk testing-basilisk
+#          ls
+#
+#      - name: Make Basilisk-node bin executanle
+#        run: |
+#          cd Basilisk-node/target/release
+#          chmod +x basilisk
+#          chmod +x testing-basilisk
+#
+#      - name: Save artifacts - Basilisk-node
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: basilisk-node-artifacts
+#          path: ./Basilisk-node
 
   #  build_app:
   #    name: Build UI application
@@ -205,7 +205,6 @@ jobs:
   run_tests:
     name: Run tests
     runs-on: ubuntu-latest
-    needs: [set_test_env_polkadot_node, set_test_env_basilisk_node]
     steps:
       - uses: actions/setup-node@v2
         with:
@@ -214,17 +213,17 @@ jobs:
       - name: Install Node.js HTTP-Server, wait-port
         run: yarn global add http-server wait-port
 
-      - name: Download artifact - Basilisk-node
-        uses: actions/download-artifact@v2
-        with:
-          name: basilisk-node-artifacts
-          path: ./Basilisk-node
-
-      - name: Download artifact - Polkadot-node
-        uses: actions/download-artifact@v2
-        with:
-          name: polkadot-node-artifacts
-          path: ./polkadot/target/release
+#      - name: Download artifact - Basilisk-node
+#        uses: actions/download-artifact@v2
+#        with:
+#          name: basilisk-node-artifacts
+#          path: ./Basilisk-node
+#
+#      - name: Download artifact - Polkadot-node
+#        uses: actions/download-artifact@v2
+#        with:
+#          name: polkadot-node-artifacts
+#          path: ./polkadot/target/release
 
       - uses: actions/checkout@v2
         with:
@@ -283,15 +282,13 @@ jobs:
 
       - name: Change folders permissions
         run: |
-          chmod -R 777 polkadot
-          chmod -R 777 Basilisk-node
           chmod -R 777 Basilisk-api
           chmod -R 777 ui-app
 
       # Prepare Rust Env
 
-      - name: Configure Rust Env
-        run: curl https://getsubstrate.io -sSf | bash -s -- --fast
+#      - name: Configure Rust Env
+#        run: curl https://getsubstrate.io -sSf | bash -s -- --fast
 
       # Run testnet
 
@@ -300,7 +297,10 @@ jobs:
         timeout-minutes: 10
         run: |
           cd Basilisk-api
-          . ./gh-actions-run-testner-with-waiting.sh
+          yarn fullruntime:clean-setup-start
+#        run: |
+#          cd Basilisk-api
+#          . ./gh-actions-run-testner-with-waiting.sh
 
       - name: Wait for Basilisk Node port :9988
         shell: bash
@@ -352,77 +352,77 @@ jobs:
 
       # Configure processor/indexer
 
-      - name: Clean and setup Processor
-        shell: bash
-        run: |
-          cd Basilisk-api
-          yarn run processor:clean-and-setup
-
-      - name: Run Indexer
-        shell: bash
-        run: |
-          cd Basilisk-api
-          yarn run indexer:start-ci-linux &
-
-      - name: Wait for Indexer port :4010
-        shell: bash
-        timeout-minutes: 5
-        run: wait-port 4010
-
-
-      - name: Sleep for 20 seconds
-        run: sleep 20s
-        shell: bash
-
-      - name: Get ips list
-        if: always()
-        shell: bash
-        timeout-minutes: 3
-        run: |
-          cd Basilisk-api/indexer
-          docker compose exec -T indexer /bin/sh
-          cat /etc/hosts
-          exit
-
-      - name: Get host ip
-        if: always()
-        shell: bash
-        timeout-minutes: 3
-        run: |
-          cd Basilisk-api/indexer
-          docker compose exec -T indexer /bin/sh
-          sudo apt-get update > /dev/null && sudo apt-get install iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
-          exit
-#  apk update > /dev/null && apk add iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
-      - name: Ping host ip
-        if: always()
-        shell: bash
-        timeout-minutes: 5
-        run: |
-          cd Basilisk-api/indexer
-          docker compose exec -T indexer /bin/sh
-          curl -s 10.1.0.1:3030 >/dev/null && echo 10.1.0.1:3030 - Success. || echo 10.1.0.1:3030 - Fail.
-          curl -s 172.17.0.1:3030 >/dev/null && echo 172.17.0.1:3030 - Success. || echo 172.17.0.1:3030 - Fail.
-          curl -s 10.1.0.1:9988 >/dev/null && echo 10.1.0.1:9988 - Success. || 10.1.0.1:9988 - echo Fail.
-          curl -s 172.17.0.1:9988 >/dev/null && echo 172.17.0.1:9988 - Success. || echo 172.17.0.1:9988 - Fail.
-
-#          npm install -g wscat
-#          wscat -c "ws://10.1.0.1:3030"
-
-      - name: Sleep for 5 seconds
-        run: sleep 5s
-        shell: bash
-
-      - name: Run Processor
-        shell: bash
-        timeout-minutes: 3
-        run: |
-          cd Basilisk-api
-          . ./gh-actions-run-processor-with-waiting.sh
-
-      - name: Sleep for 5 seconds
-        run: sleep 5s
-        shell: bash
+#      - name: Clean and setup Processor
+#        shell: bash
+#        run: |
+#          cd Basilisk-api
+#          yarn run processor:clean-and-setup
+#
+#      - name: Run Indexer
+#        shell: bash
+#        run: |
+#          cd Basilisk-api
+#          yarn run indexer:start-ci-linux &
+#
+#      - name: Wait for Indexer port :4010
+#        shell: bash
+#        timeout-minutes: 5
+#        run: wait-port 4010
+#
+#
+#      - name: Sleep for 20 seconds
+#        run: sleep 20s
+#        shell: bash
+#
+#      - name: Get ips list
+#        if: always()
+#        shell: bash
+#        timeout-minutes: 3
+#        run: |
+#          cd Basilisk-api/indexer
+#          docker compose exec -T indexer /bin/sh
+#          cat /etc/hosts
+#          exit
+#
+#      - name: Get host ip
+#        if: always()
+#        shell: bash
+#        timeout-minutes: 3
+#        run: |
+#          cd Basilisk-api/indexer
+#          docker compose exec -T indexer /bin/sh
+#          sudo apt-get update > /dev/null && sudo apt-get install iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
+#          exit
+##  apk update > /dev/null && apk add iproute2 > /dev/null && ip -4 route show default | cut -d' ' -f3
+#      - name: Ping host ip
+#        if: always()
+#        shell: bash
+#        timeout-minutes: 5
+#        run: |
+#          cd Basilisk-api/indexer
+#          docker compose exec -T indexer /bin/sh
+#          curl -s 10.1.0.1:3030 >/dev/null && echo 10.1.0.1:3030 - Success. || echo 10.1.0.1:3030 - Fail.
+#          curl -s 172.17.0.1:3030 >/dev/null && echo 172.17.0.1:3030 - Success. || echo 172.17.0.1:3030 - Fail.
+#          curl -s 10.1.0.1:9988 >/dev/null && echo 10.1.0.1:9988 - Success. || 10.1.0.1:9988 - echo Fail.
+#          curl -s 172.17.0.1:9988 >/dev/null && echo 172.17.0.1:9988 - Success. || echo 172.17.0.1:9988 - Fail.
+#
+##          npm install -g wscat
+##          wscat -c "ws://10.1.0.1:3030"
+#
+#      - name: Sleep for 5 seconds
+#        run: sleep 5s
+#        shell: bash
+#
+#      - name: Run Processor
+#        shell: bash
+#        timeout-minutes: 3
+#        run: |
+#          cd Basilisk-api
+#          . ./gh-actions-run-processor-with-waiting.sh
+#
+#      - name: Sleep for 5 seconds
+#        run: sleep 5s
+#        shell: bash
 
       - name: Check Docker containers
         if: always()
